language: python

env:
 - PORT=5010
install:
  - pip install -U pip
  - pip install --upgrade pip
  - pip install -r requirements.txt

# command to run tests
#script: python tests.py
script: echo "tests"

deploy:
   edge: true
   provider: cloudfoundry
   username: vnirmalkumarece@gmail.com
   password: Karuvadu123
   api: https://api.run.pivotal.io
   organization: voice
   space: development